# Generated by Django 6.0.5 on 2026-05-21 02:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude')], max_length=20, unique=True, verbose_name='Proveedor')),
                ('model_name', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o mini'), ('claude-haiku-4-5', 'Claude Haiku 4.5')], help_text='Seleccione un modelo válido para el proveedor elegido.', max_length=100, verbose_name='Modelo')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Un número menor significa mayor prioridad.', verbose_name='Prioridad')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('timeout_seconds', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Segundos de espera antes de agotar el intento (acepta decimales).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tiempo máximo de espera')),
                ('max_retries', models.PositiveIntegerField(default=2, verbose_name='Reintentos máximos')),
                ('failure_policy', models.CharField(blank=True, choices=[('fallback', 'Cambiar al siguiente proveedor')], default='fallback', max_length=20, verbose_name='Política de fallo')),
                ('failure_threshold', models.PositiveIntegerField(default=1, help_text='Cantidad de fallos consecutivos antes de considerar degradado el proveedor.', verbose_name='Umbral de fallos')),
                ('cooldown_seconds', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Segundos de espera antes de volver a intentar usar este proveedor (acepta decimales).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tiempo de enfriamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración de proveedor de IA',
                'verbose_name_plural': 'Configuraciones de proveedores de IA',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('use_case', models.CharField(choices=[('chat_extraction', 'Extracción de datos del chat'), ('spam_validation', 'Validación de spam'), ('lead_analysis', 'Análisis de leads'), ('lead_priority', 'Priorización de leads'), ('generic', 'Uso general')], max_length=100, verbose_name='Caso de uso')),
                ('provider', models.CharField(choices=[('all', 'Todos los proveedores'), ('openai', 'OpenAI'), ('claude', 'Claude')], default='all', max_length=20, verbose_name='Proveedor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('system_prompt', models.TextField(verbose_name='Prompt del sistema')),
                ('user_prompt_template', models.TextField(verbose_name='Plantilla del prompt de usuario')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de prompt de IA',
                'verbose_name_plural': 'Plantillas de prompts de IA',
                'ordering': ('use_case', '-version'),
                'indexes': [models.Index(fields=['use_case', 'provider', 'is_active'], name='ai_manage_a_use_cas_df8689_idx')],
                'unique_together': {('name', 'use_case', 'provider', 'version')},
            },
        ),
    ]
