# Generated by Django 6.0.5 on 2026-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprompttemplate',
            options={'ordering': ('use_case', 'name'), 'verbose_name': 'Plantilla de prompt de IA', 'verbose_name_plural': 'Plantillas de prompts de IA'},
        ),
        migrations.RemoveIndex(
            model_name='aiprompttemplate',
            name='ai_manage_a_use_cas_df8689_idx',
        ),
        migrations.AlterUniqueTogether(
            name='aiprompttemplate',
            unique_together={('name', 'use_case')},
        ),
        migrations.AddIndex(
            model_name='aiprompttemplate',
            index=models.Index(fields=['use_case', 'is_active'], name='ai_manage_a_use_cas_9321fd_idx'),
        ),
        migrations.RemoveField(
            model_name='aiprompttemplate',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiprompttemplate',
            name='version',
        ),
    ]
