# Generated by Django 6.0.5 on 2026-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manage', '0002_alter_aiprompttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='use_case',
            field=models.CharField(choices=[('chat_extraction', 'Extracción de datos del chat'), ('spam_validation', 'Validación de spam'), ('lead_analysis', 'Análisis de leads'), ('lead_priority', 'Priorización de leads'), ('lead_capture_extraction', 'Extracción de datos de lead'), ('generic', 'Uso general')], max_length=100, verbose_name='Caso de uso'),
        ),
    ]
