# Generated by Django 6.0.5 on 2026-05-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('disponibilidad', models.CharField(blank=True, max_length=255)),
                ('mensaje_original', models.TextField(blank=True)),
                ('datos_extraidos_json', models.JSONField(blank=True, default=dict)),
                ('datos_faltantes_json', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completado'), ('abandoned', 'Abandonado')], default='in_progress', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('confidence_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_captures', to='widget.widgetconversation')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
