# Generated by Django 6.0.5 on 2026-05-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_leadcapture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('disponibilidad', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completado'), ('abandoned', 'Abandonado')], default='in_progress', max_length=20)),
                ('fuente', models.CharField(default='widget', max_length=100)),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='widget.widgetconversation')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.DeleteModel(
            name='LeadCapture',
        ),
    ]
