# Generated by Django 6.0.5 on 2026-05-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_lead_delete_leadcapture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
