# Generated by Django 6.0.5 on 2026-05-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_delete_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconversation',
            name='lead_state',
            field=models.JSONField(blank=True, default=dict, help_text='Estado temporal de la captura de lead'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('disponibilidad', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('completed', 'Completado'), ('incomplete', 'Incompleto')], default='completed', max_length=20)),
                ('fuente', models.CharField(default='widget', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='widget.widgetconversation')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
            },
        ),
    ]
