# Generated by Django 6.0.5 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widget", "0005_create_widgetflowblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetflowblock",
            name="validation_type",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("telefono", "Teléfono"),
                    ("email", "Email"),
                    ("horario", "Horario"),
                    ("ninguno", "Ninguno"),
                ],
                default="ninguno",
                help_text="Tipo de validación esperada para el bloque.",
                max_length=20,
            ),
        ),
    ]
